server:
  port: 8021
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: AsmarinO2009?
    url: jdbc:mysql://localhost:3306/stock-qa
    username: root
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
