server:
  port: 8020
spring:
  datasource:
    password: India@123
    url: jdbc:mysql://localhost:3306/stock-prod?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
